controller_list:
  - name: fake_ur5e_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: ur5e_arm
    pose: home_pose